"""Questions endpoint — serves the static question bank, filtered by level/subject.

Questions live in backend/questions.json (generated by scripts/generateQuestions.mjs).
The file is loaded once at first request and cached in memory for the process lifetime.
Filtering happens in Python so the client only receives the questions it needs,
keeping the response payload ~50-100x smaller than shipping the full bank.
"""
import json
import os
from functools import lru_cache
from typing import Optional

from fastapi import APIRouter, Query

router = APIRouter()

_QUESTIONS_PATH = os.path.join(os.path.dirname(__file__), "questions.json")


@lru_cache(maxsize=1)
def _load_bank() -> list:
    """Load and cache the full question bank from disk."""
    with open(_QUESTIONS_PATH, encoding="utf-8") as f:
        return json.load(f)


@router.get("/questions")
def get_questions(
    level: Optional[str] = Query(None, description="e.g. ks2, ks3, gcse, alevel"),
    subject: Optional[str] = Query(None, description="e.g. maths, physics"),
):
    """Return questions filtered by level and/or subject.

    Both params are optional — omit to get the full bank (not recommended in production).
    """
    bank = _load_bank()
    result = bank
    if level:
        result = [q for q in result if q["level"] == level]
    if subject:
        result = [q for q in result if q["subject"] == subject]
    return result
