"""Append-only KS2 Physics questions to backend/questions.json and src/data/questions.js.
Run from repo root: python scripts/append_ks2_physics.py
"""
import json, os, re, sys

QUESTIONS = [
  # ── Forces & magnets ────────────────────────────────────────────────────
  {"id":"ks2_ph_forces_magnets_0001","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What is a force?","options":{"A":"A push or a pull","B":"A type of energy","C":"The speed of an object","D":"The weight of an object"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0002","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these objects is made from a magnetic material?","options":{"A":"Wooden spoon","B":"Iron nail","C":"Plastic cup","D":"Glass bottle"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0003","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Two north poles are brought close together. What will happen?","options":{"A":"They attract each other","B":"They stick together","C":"They repel (push away) each other","D":"Nothing happens"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0004","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What type of force needs two objects to be touching?","options":{"A":"Gravity","B":"Magnetism","C":"Non-contact force","D":"Contact force"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0005","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Gravity is an example of a...","options":{"A":"Non-contact force","B":"Contact force","C":"Friction force","D":"Push force"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0006","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A north pole and a south pole are placed close together. They will...","options":{"A":"Repel each other","B":"Attract each other","C":"Stay completely still","D":"Rotate"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0007","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which material is NOT attracted by a magnet?","options":{"A":"Iron","B":"Steel","C":"Copper","D":"Nickel"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0008","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Magnetism is an example of a...","options":{"A":"Contact force","B":"Push force","C":"Friction force","D":"Non-contact force"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0009","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What do we call the ends of a bar magnet?","options":{"A":"Poles","B":"Tips","C":"Ends","D":"Edges"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0010","level":"ks2","subject":"physics","category":"Forces & magnets","text":"How many poles does a bar magnet have?","options":{"A":"One","B":"Two","C":"Three","D":"Four"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0011","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these best describes a contact force?","options":{"A":"Gravity pulling you down","B":"A magnet attracting a nail","C":"Pushing a door open","D":"Earth pulling the Moon"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0012","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A horseshoe magnet has its north and south poles...","options":{"A":"Both at the same end","B":"In the middle","C":"Far apart on the same side","D":"At each open end"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0013","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these is a magnetic material?","options":{"A":"Steel","B":"Copper","C":"Aluminium","D":"Wood"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0014","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What happens when you put two south poles together?","options":{"A":"They attract each other","B":"They repel each other","C":"They stick together","D":"Nothing happens"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0015","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A compass needle always points toward which direction?","options":{"A":"South","B":"East","C":"North","D":"West"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0016","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What makes a compass needle move?","options":{"A":"The weight of the needle","B":"The Sun's gravity","C":"Air blowing on the needle","D":"Earth's magnetic field"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0017","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these would a magnet be UNABLE to work through?","options":{"A":"A thick iron sheet","B":"Water","C":"Paper","D":"Air"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0018","level":"ks2","subject":"physics","category":"Forces & magnets","text":"If you push a toy car along a carpet, you are applying a...","options":{"A":"Non-contact force","B":"Contact force","C":"Magnetic force","D":"Gravity force"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0019","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which three metals are magnetic?","options":{"A":"Gold, silver and bronze","B":"Copper, tin and zinc","C":"Iron, steel and nickel","D":"Lead, aluminium and brass"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0020","level":"ks2","subject":"physics","category":"Forces & magnets","text":"When you squeeze a sponge, you are using a...","options":{"A":"Pull force","B":"Twist force","C":"Gravity force","D":"Push (squashing) force"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0021","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What is the name of the force between a magnet and a magnetic material?","options":{"A":"Magnetic force","B":"Gravity","C":"Air resistance","D":"Friction"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0022","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A magnet is brought near an iron nail. The nail is attracted to...","options":{"A":"Only the north pole","B":"Either pole of the magnet","C":"Only the south pole","D":"Neither pole"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0023","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these is an example of a pull force?","options":{"A":"Kicking a football","B":"Pushing a swing","C":"Stretching a rubber band","D":"Pressing a button"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0024","level":"ks2","subject":"physics","category":"Forces & magnets","text":"You can make a temporary magnet by...","options":{"A":"Painting iron with metal paint","B":"Cooling iron in water","C":"Heating iron until it glows","D":"Stroking iron many times with a magnet in one direction"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0025","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which of these is NOT a contact force?","options":{"A":"Gravity","B":"Pushing","C":"Pulling","D":"Friction"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0026","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A force can change which of these?","options":{"A":"The colour of an object","B":"The shape, speed or direction of an object","C":"The temperature of an object","D":"The material an object is made from"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0027","level":"ks2","subject":"physics","category":"Forces & magnets","text":"The magnetic force of a bar magnet is greatest at...","options":{"A":"Its centre","B":"Along its sides","C":"Its poles","D":"Everywhere equally"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0028","level":"ks2","subject":"physics","category":"Forces & magnets","text":"What unit do we use to measure force?","options":{"A":"Kilogram","B":"Metre","C":"Second","D":"Newton"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_magnets_0029","level":"ks2","subject":"physics","category":"Forces & magnets","text":"A stretching force is also called a...","options":{"A":"Tension force","B":"Compression force","C":"Friction force","D":"Magnetic force"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_forces_magnets_0030","level":"ks2","subject":"physics","category":"Forces & magnets","text":"Which statement about magnets is TRUE?","options":{"A":"Like poles attract","B":"Opposite poles attract","C":"All metals are magnetic","D":"Magnets only work when touching"},"correct":"B","difficulty":1},

  # ── Light & shadows ──────────────────────────────────────────────────────
  {"id":"ks2_ph_light_0001","level":"ks2","subject":"physics","category":"Light & shadows","text":"The Sun is a light source. What does this mean?","options":{"A":"It makes its own light","B":"It reflects light from the Moon","C":"It gets light from Earth","D":"It stores light during the day"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0002","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of these objects is NOT a light source?","options":{"A":"A candle flame","B":"A mirror","C":"A light bulb","D":"The Sun"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0003","level":"ks2","subject":"physics","category":"Light & shadows","text":"A material that lets NO light through is called...","options":{"A":"Transparent","B":"Translucent","C":"Opaque","D":"Reflective"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0004","level":"ks2","subject":"physics","category":"Light & shadows","text":"A material that lets ALL light through clearly is called...","options":{"A":"Opaque","B":"Translucent","C":"Reflective","D":"Transparent"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_light_0005","level":"ks2","subject":"physics","category":"Light & shadows","text":"How do we see an object that is not a light source?","options":{"A":"Light bounces (reflects) off it into our eyes","B":"The object gives off its own light","C":"Our eyes produce light to look at it","D":"The air around it glows"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0006","level":"ks2","subject":"physics","category":"Light & shadows","text":"When does a shadow form?","options":{"A":"When light passes through an object","B":"When an opaque object blocks light","C":"When a transparent object reflects light","D":"When the Sun sets"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0007","level":"ks2","subject":"physics","category":"Light & shadows","text":"A shadow always forms on which side of an object?","options":{"A":"The same side as the light source","B":"Underneath the object","C":"The opposite side to the light source","D":"In front of the object"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0008","level":"ks2","subject":"physics","category":"Light & shadows","text":"What happens to a shadow when the light source is moved closer to the object?","options":{"A":"The shadow disappears","B":"The shadow gets smaller","C":"The shadow stays the same","D":"The shadow gets bigger"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_light_0009","level":"ks2","subject":"physics","category":"Light & shadows","text":"What is a material that lets some light through but scatters it?","options":{"A":"Translucent","B":"Opaque","C":"Transparent","D":"Reflective"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0010","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of these is a source of light?","options":{"A":"A book","B":"A torch","C":"A tree","D":"A stone"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0011","level":"ks2","subject":"physics","category":"Light & shadows","text":"Light travels in...","options":{"A":"Curves","B":"Circles","C":"Straight lines","D":"Spirals"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0012","level":"ks2","subject":"physics","category":"Light & shadows","text":"A window made of clear glass is an example of a...","options":{"A":"Opaque material","B":"Translucent material","C":"Absorbing material","D":"Transparent material"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_light_0013","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of these creates a shadow on a sunny day?","options":{"A":"Holding a cardboard box in sunlight","B":"Shining a torch through a clear glass window","C":"Placing a mirror in sunlight","D":"Looking through a transparent sheet"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0014","level":"ks2","subject":"physics","category":"Light & shadows","text":"Why can we see the Moon at night?","options":{"A":"The Moon makes its own light","B":"The Moon reflects light from the Sun","C":"The Moon stores sunlight and releases it at night","D":"Stars shine directly onto the Moon"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_light_0015","level":"ks2","subject":"physics","category":"Light & shadows","text":"Frosted glass is an example of which type of material?","options":{"A":"Transparent","B":"Opaque","C":"Translucent","D":"Reflective"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0016","level":"ks2","subject":"physics","category":"Light & shadows","text":"A shadow has the same outline as...","options":{"A":"The light source","B":"The background surface","C":"The space around the object","D":"The object blocking the light"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_light_0017","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which statement about how we see is CORRECT?","options":{"A":"Light travels from a source, bounces off objects, and enters our eyes","B":"Our eyes send out beams of light to touch objects","C":"Objects glow when we look at them","D":"Light travels from our eyes to objects and back"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0018","level":"ks2","subject":"physics","category":"Light & shadows","text":"When is a shadow longest — when the Sun is low or high in the sky?","options":{"A":"When the Sun is high in the sky","B":"When the Sun is low in the sky","C":"Shadows are always the same length","D":"The Sun does not affect shadow length"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0019","level":"ks2","subject":"physics","category":"Light & shadows","text":"A brick wall does not let light through. It is...","options":{"A":"Translucent","B":"Transparent","C":"Opaque","D":"Reflective"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0020","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which colour reflects all light and appears white?","options":{"A":"Black","B":"Blue","C":"Red","D":"White"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_light_0021","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which colour absorbs most light?","options":{"A":"Black","B":"White","C":"Yellow","D":"Green"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0022","level":"ks2","subject":"physics","category":"Light & shadows","text":"When light hits a mirror, it...","options":{"A":"Is absorbed and disappears","B":"Reflects (bounces back)","C":"Passes straight through","D":"Bends downward"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0023","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of the following would produce the BEST shadow on a screen?","options":{"A":"A sheet of clear glass","B":"A sheet of tissue paper","C":"A sheet of cardboard","D":"A sheet of tracing paper"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_light_0024","level":"ks2","subject":"physics","category":"Light & shadows","text":"Sunlight can be split into many colours. What device does this?","options":{"A":"A mirror","B":"A lens","C":"A telescope","D":"A prism"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_light_0025","level":"ks2","subject":"physics","category":"Light & shadows","text":"At midday, when the Sun is directly overhead, your shadow will be...","options":{"A":"Very short","B":"Very long","C":"Behind you","D":"In front of you"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_light_0026","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of these objects is transparent?","options":{"A":"A wooden door","B":"A clear plastic ruler","C":"A piece of cardboard","D":"A woollen jumper"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_light_0027","level":"ks2","subject":"physics","category":"Light & shadows","text":"Light from the Sun takes about 8 minutes to reach Earth. This shows that light...","options":{"A":"Travels very slowly","B":"Does not travel — it appears everywhere at once","C":"Travels very fast","D":"Gets slower as it travels"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_light_0028","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which material would make the LARGEST shadow when held in front of a torch?","options":{"A":"A clear glass","B":"A piece of tissue paper","C":"A piece of tracing paper","D":"A thick piece of cardboard"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_light_0029","level":"ks2","subject":"physics","category":"Light & shadows","text":"Which of these would be the BEST reflector of light?","options":{"A":"A polished metal spoon","B":"A rough stone","C":"A piece of wood","D":"A crumpled piece of paper"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_light_0030","level":"ks2","subject":"physics","category":"Light & shadows","text":"You can read writing on a page because light...","options":{"A":"Is created inside the page","B":"Reflects off the page into your eyes","C":"Passes through the page","D":"Is created by your eyes"},"correct":"B","difficulty":1},

  # ── Sound ────────────────────────────────────────────────────────────────
  {"id":"ks2_ph_sound_0001","level":"ks2","subject":"physics","category":"Sound","text":"What causes sound?","options":{"A":"Vibrations","B":"Gravity","C":"Light waves","D":"Heat"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0002","level":"ks2","subject":"physics","category":"Sound","text":"If you pluck a guitar string and then hold it to stop it vibrating, the sound...","options":{"A":"Gets louder","B":"Stops","C":"Carries on the same","D":"Gets higher"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0003","level":"ks2","subject":"physics","category":"Sound","text":"Sound travels best through...","options":{"A":"A vacuum (empty space)","B":"Air","C":"Solid materials like metal","D":"Sound travels the same through everything"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_sound_0004","level":"ks2","subject":"physics","category":"Sound","text":"You are standing far from a loudspeaker. As you walk closer, the sound becomes...","options":{"A":"Lower pitch","B":"Higher pitch","C":"The same volume","D":"Louder"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0005","level":"ks2","subject":"physics","category":"Sound","text":"What is pitch?","options":{"A":"How high or low a sound is","B":"How loud a sound is","C":"The speed of sound","D":"The colour of a sound wave"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0006","level":"ks2","subject":"physics","category":"Sound","text":"A high-pitched sound is made when something vibrates...","options":{"A":"Slowly","B":"Quickly","C":"Once","D":"Heavily"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0007","level":"ks2","subject":"physics","category":"Sound","text":"Can sound travel through water?","options":{"A":"No, sound cannot travel through liquids","B":"No, sound travels only through air","C":"Yes, sound can travel through liquids","D":"Only if the water is very warm"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_sound_0008","level":"ks2","subject":"physics","category":"Sound","text":"What is volume (in the context of sound)?","options":{"A":"The pitch of a sound","B":"The speed of a sound","C":"The type of material sound travels through","D":"How loud or quiet a sound is"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0009","level":"ks2","subject":"physics","category":"Sound","text":"A tight, thin guitar string makes a...","options":{"A":"Higher-pitched sound","B":"Lower-pitched sound","C":"Louder sound","D":"Quieter sound"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0010","level":"ks2","subject":"physics","category":"Sound","text":"A longer, looser drum skin makes a...","options":{"A":"Higher-pitched sound","B":"Lower-pitched sound","C":"Louder sound","D":"No sound"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0011","level":"ks2","subject":"physics","category":"Sound","text":"Can sound travel through a vacuum (empty space)?","options":{"A":"Yes, it travels fastest through a vacuum","B":"Yes, but slowly","C":"No, sound needs a medium (material) to travel through","D":"Yes, this is how sounds from space reach us"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_sound_0012","level":"ks2","subject":"physics","category":"Sound","text":"A sound is made louder by...","options":{"A":"Slowing down the vibrations","B":"Speeding up the vibrations","C":"Changing the pitch","D":"Increasing the size of the vibrations"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0013","level":"ks2","subject":"physics","category":"Sound","text":"Which sense organ do we use to detect sounds?","options":{"A":"Ears","B":"Eyes","C":"Nose","D":"Skin"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0014","level":"ks2","subject":"physics","category":"Sound","text":"How does sound travel from a vibrating object to your ear?","options":{"A":"It travels as light","B":"It makes the surrounding material vibrate","C":"It jumps through the air instantly","D":"Your ears reach out to the source"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0015","level":"ks2","subject":"physics","category":"Sound","text":"Bats use high-pitched squeaks that bounce back from objects to find their way. This is called...","options":{"A":"Reflection","B":"Resonance","C":"Echolocation","D":"Vibration"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_sound_0016","level":"ks2","subject":"physics","category":"Sound","text":"A drum makes a louder sound when you...","options":{"A":"Tap it lightly","B":"Tap it with your finger only","C":"Tap it slowly","D":"Hit it harder"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0017","level":"ks2","subject":"physics","category":"Sound","text":"Sound becomes quieter as you move further from the source because...","options":{"A":"The energy spreads out over a larger area","B":"The sound slows down","C":"The pitch gets lower","D":"The air blocks the sound"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_sound_0018","level":"ks2","subject":"physics","category":"Sound","text":"What do we call a material that absorbs sound well?","options":{"A":"A reflector","B":"A sound absorber (like foam or thick curtains)","C":"A conductor","D":"A transmitter"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0019","level":"ks2","subject":"physics","category":"Sound","text":"Which of these would make the HIGHEST-pitched sound?","options":{"A":"A large bass drum","B":"A long thick string","C":"A small triangle","D":"A large gong"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_sound_0020","level":"ks2","subject":"physics","category":"Sound","text":"Approximately how fast does sound travel through air?","options":{"A":"3 km per second","B":"300,000 km per second","C":"30 km per second","D":"340 metres per second"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_sound_0021","level":"ks2","subject":"physics","category":"Sound","text":"When you speak, the sound comes from vibrations in your...","options":{"A":"Vocal cords","B":"Tongue","C":"Lips","D":"Teeth"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0022","level":"ks2","subject":"physics","category":"Sound","text":"If you stretch a rubber band tighter and pluck it, the sound becomes...","options":{"A":"Quieter","B":"Higher in pitch","C":"Lower in pitch","D":"Louder"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0023","level":"ks2","subject":"physics","category":"Sound","text":"Which of the following best describes how a sound wave travels?","options":{"A":"It carries pieces of air to your ear","B":"It carries light energy","C":"It causes the material to vibrate and passes the vibration on","D":"It travels as heat energy"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_sound_0024","level":"ks2","subject":"physics","category":"Sound","text":"You see a flash of lightning before you hear the thunder. What does this tell you?","options":{"A":"Thunder is louder than lightning","B":"Lightning and thunder happen at different times","C":"Sound and light travel at the same speed","D":"Light travels faster than sound"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0025","level":"ks2","subject":"physics","category":"Sound","text":"A whisper is quieter than a shout because the vibrations are...","options":{"A":"Smaller (lower amplitude)","B":"Lower in pitch","C":"Faster","D":"Slower"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_sound_0026","level":"ks2","subject":"physics","category":"Sound","text":"To show that sound is caused by vibrations, the best investigation is...","options":{"A":"Shining a torch on a drum skin","B":"Putting rice grains on a drum skin and hitting the drum","C":"Filling a drum with water","D":"Heating a drum with a hairdryer"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_sound_0027","level":"ks2","subject":"physics","category":"Sound","text":"Which of these absorbs sound MOST?","options":{"A":"Hard wooden floor","B":"Glass windows","C":"Thick carpet","D":"Stone walls"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_sound_0028","level":"ks2","subject":"physics","category":"Sound","text":"To make a quieter sound on a guitar, you would...","options":{"A":"Stretch the string tighter","B":"Use a thinner string","C":"Press the string against a fret","D":"Pluck the string more gently"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_sound_0029","level":"ks2","subject":"physics","category":"Sound","text":"Can sound travel through a solid material?","options":{"A":"Yes","B":"No, only through air","C":"No, only through liquids","D":"No, sound cannot travel through any material"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_sound_0030","level":"ks2","subject":"physics","category":"Sound","text":"The eardrum vibrates when sound reaches it. What does the eardrum do?","options":{"A":"Creates sounds of its own","B":"Passes the vibrations to the inner ear so you can hear","C":"Blocks loud sounds to protect you","D":"Absorbs all sounds that arrive"},"correct":"B","difficulty":1},

  # ── Electricity ──────────────────────────────────────────────────────────
  {"id":"ks2_ph_electricity_0001","level":"ks2","subject":"physics","category":"Electricity","text":"In a circuit, what does a battery (cell) do?","options":{"A":"Provides the energy to make electricity flow","B":"Stops the electricity flowing","C":"Makes electricity from light","D":"Measures the electricity"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0002","level":"ks2","subject":"physics","category":"Electricity","text":"In a simple circuit, what does a switch do?","options":{"A":"Makes bulbs brighter","B":"Opens or closes the circuit","C":"Provides power to the circuit","D":"Changes the colour of the bulb"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_electricity_0003","level":"ks2","subject":"physics","category":"Electricity","text":"A material that lets electricity flow through it is called a...","options":{"A":"Insulator","B":"Resistor","C":"Conductor","D":"Reflector"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0004","level":"ks2","subject":"physics","category":"Electricity","text":"A material that does NOT let electricity flow through it is called an...","options":{"A":"Conductor","B":"Reflector","C":"Transmitter","D":"Insulator"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0005","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these materials is a GOOD conductor of electricity?","options":{"A":"Copper wire","B":"Rubber","C":"Wood","D":"Plastic"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0006","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these is a good insulator?","options":{"A":"Copper","B":"Rubber","C":"Iron","D":"Aluminium"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_electricity_0007","level":"ks2","subject":"physics","category":"Electricity","text":"In a series circuit, what happens if you remove one bulb?","options":{"A":"The other bulbs get brighter","B":"The other bulbs stay the same","C":"All the bulbs go out","D":"Only the removed bulb goes out"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0008","level":"ks2","subject":"physics","category":"Electricity","text":"If you add more batteries to a circuit, the bulb will...","options":{"A":"Go off","B":"Stay the same","C":"Get dimmer","D":"Get brighter"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0009","level":"ks2","subject":"physics","category":"Electricity","text":"In a circuit diagram, a battery is shown as...","options":{"A":"Two parallel lines, one longer than the other","B":"A circle with a cross","C":"A zigzag line","D":"An X inside a circle"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_electricity_0010","level":"ks2","subject":"physics","category":"Electricity","text":"What does a buzzer do in a circuit?","options":{"A":"Lights up","B":"Makes a buzzing sound","C":"Measures current","D":"Stops the circuit"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_electricity_0011","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these would complete a circuit and make a bulb light up?","options":{"A":"Connecting a plastic strip between the wires","B":"Leaving a gap in the wires","C":"Connecting a copper wire between the open ends","D":"Adding a rubber band to the circuit"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0012","level":"ks2","subject":"physics","category":"Electricity","text":"Each individual part of a circuit (bulb, switch, battery) is called a...","options":{"A":"Battery","B":"Switch","C":"Conductor","D":"Component"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0013","level":"ks2","subject":"physics","category":"Electricity","text":"A motor in a circuit will...","options":{"A":"Spin or move","B":"Light up","C":"Make a ringing sound","D":"Measure voltage"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0014","level":"ks2","subject":"physics","category":"Electricity","text":"Why do electrical wires have a plastic coating?","options":{"A":"To make them stronger","B":"To insulate them and prevent electric shocks","C":"To make the electricity travel faster","D":"To keep the wire warm"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_electricity_0015","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these would allow a bulb to light up when connected in a circuit?","options":{"A":"A piece of wood","B":"A plastic straw","C":"A metal spoon","D":"A rubber glove"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0016","level":"ks2","subject":"physics","category":"Electricity","text":"If you add more bulbs in a series circuit, the bulbs get...","options":{"A":"Brighter","B":"The same brightness","C":"They turn off completely","D":"Dimmer"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_electricity_0017","level":"ks2","subject":"physics","category":"Electricity","text":"What is the purpose of a switch in a circuit?","options":{"A":"To turn the circuit on and off","B":"To make the bulb brighter","C":"To add more power","D":"To measure electricity"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0018","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these describes a complete (closed) circuit?","options":{"A":"Battery, wire, gap, bulb","B":"Battery, wire, bulb, wire, back to battery","C":"Battery, wire, open switch, bulb","D":"Wire, bulb, wire, gap"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_electricity_0019","level":"ks2","subject":"physics","category":"Electricity","text":"In a series circuit with two bulbs, if one bulb blows, what happens to the other?","options":{"A":"It gets brighter","B":"It stays the same","C":"It goes out","D":"It flashes"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0020","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these would NOT conduct electricity?","options":{"A":"A steel ruler","B":"A copper coin","C":"An aluminium can","D":"A glass bottle"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0021","level":"ks2","subject":"physics","category":"Electricity","text":"When is a switch said to be 'closed'?","options":{"A":"When it is switched on and lets electricity flow","B":"When it is switched off","C":"When it breaks the circuit","D":"When it stops electricity"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0022","level":"ks2","subject":"physics","category":"Electricity","text":"What happens to a bulb in a circuit when you use a bigger battery?","options":{"A":"The bulb gets dimmer","B":"The bulb gets brighter","C":"The bulb flashes","D":"Nothing changes"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_electricity_0023","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these is a component that creates light in a circuit?","options":{"A":"A battery","B":"A switch","C":"A bulb","D":"A wire"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_electricity_0024","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these is an example of an insulator?","options":{"A":"Copper","B":"Steel","C":"Iron","D":"Plastic"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0025","level":"ks2","subject":"physics","category":"Electricity","text":"Which device uses electricity to create movement?","options":{"A":"A motor","B":"A buzzer","C":"A bulb","D":"A battery"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_electricity_0026","level":"ks2","subject":"physics","category":"Electricity","text":"What would happen if you connected a wire directly between the two terminals of a battery WITHOUT a bulb?","options":{"A":"Nothing would happen","B":"A short circuit would form and the battery would drain very quickly","C":"The battery would get bigger","D":"The wire would glow and make light"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_electricity_0027","level":"ks2","subject":"physics","category":"Electricity","text":"Electrical safety — which of these should you NEVER do?","options":{"A":"Use a plastic plug cover","B":"Turn off a switch before changing a bulb","C":"Keep wires tidily out of the way","D":"Put metal objects into an electrical socket"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_electricity_0028","level":"ks2","subject":"physics","category":"Electricity","text":"Which statement about a series circuit is TRUE?","options":{"A":"Each component has its own loop","B":"Components can be switched on and off independently","C":"There is only one path for electricity to flow","D":"Removing one component does not affect the others"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_electricity_0029","level":"ks2","subject":"physics","category":"Electricity","text":"How could you make a bulb in a series circuit brighter WITHOUT adding more batteries?","options":{"A":"Reduce the number of other bulbs in the circuit","B":"Add more switches","C":"Use a longer wire","D":"Open one of the switches"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_electricity_0030","level":"ks2","subject":"physics","category":"Electricity","text":"Which of these circuits would make a bulb light up?","options":{"A":"An open circuit with one switch open","B":"A closed circuit with the switch closed","C":"A circuit with a gap in the wire","D":"A circuit with only insulators"},"correct":"B","difficulty":1},

  # ── Forces & motion ──────────────────────────────────────────────────────
  {"id":"ks2_ph_forces_motion_0001","level":"ks2","subject":"physics","category":"Forces & motion","text":"What is gravity?","options":{"A":"A force that pulls objects towards each other","B":"A force that pushes objects apart","C":"The weight of an object","D":"A type of magnet"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_motion_0002","level":"ks2","subject":"physics","category":"Forces & motion","text":"What force slows down a car's tyres on a road?","options":{"A":"Air resistance","B":"Friction","C":"Gravity","D":"Water resistance"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_motion_0003","level":"ks2","subject":"physics","category":"Forces & motion","text":"When a parachutist falls from a plane, what force slows them down?","options":{"A":"Gravity","B":"Friction","C":"Air resistance","D":"Water resistance"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0004","level":"ks2","subject":"physics","category":"Forces & motion","text":"A streamlined shape is designed to...","options":{"A":"Increase friction","B":"Increase air resistance","C":"Increase weight","D":"Reduce air resistance"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_motion_0005","level":"ks2","subject":"physics","category":"Forces & motion","text":"What is the unit used to measure force?","options":{"A":"Newton","B":"Kilogram","C":"Metre","D":"Second"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_motion_0006","level":"ks2","subject":"physics","category":"Forces & motion","text":"What happens to water resistance as a swimmer moves faster?","options":{"A":"Friction decreases","B":"Water resistance increases","C":"Gravity decreases","D":"Gravity increases"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_motion_0007","level":"ks2","subject":"physics","category":"Forces & motion","text":"A lever is a simple machine. What does it help you do?","options":{"A":"Move objects with more friction","B":"Increase the weight of an object","C":"Lift or move a heavy load with less effort","D":"Reduce gravity"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0008","level":"ks2","subject":"physics","category":"Forces & motion","text":"What instrument is used to measure force?","options":{"A":"A thermometer","B":"A ruler","C":"A voltmeter","D":"A force meter (Newton meter)"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_motion_0009","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which planet has the strongest gravitational pull?","options":{"A":"Jupiter","B":"Mars","C":"Saturn","D":"Mercury"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_forces_motion_0010","level":"ks2","subject":"physics","category":"Forces & motion","text":"Rough surfaces create _______ friction compared to smooth surfaces.","options":{"A":"Less","B":"More","C":"The same","D":"No"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_motion_0011","level":"ks2","subject":"physics","category":"Forces & motion","text":"A fish has a streamlined shape. This helps it to...","options":{"A":"Float in water","B":"Look attractive to other fish","C":"Move more easily through the water","D":"Breathe underwater"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0012","level":"ks2","subject":"physics","category":"Forces & motion","text":"What effect does gravity have on objects in mid-air?","options":{"A":"It pushes them upward","B":"It slows them horizontally","C":"It has no effect","D":"It pulls them downward"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_motion_0013","level":"ks2","subject":"physics","category":"Forces & motion","text":"Air resistance acts in which direction on a falling object?","options":{"A":"Upward (opposing the motion)","B":"Downward (same direction as gravity)","C":"Sideways","D":"In all directions equally"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_motion_0014","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which of these would experience MORE air resistance?","options":{"A":"A tiny marble","B":"An open parachute","C":"A stone","D":"A tennis ball"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_motion_0015","level":"ks2","subject":"physics","category":"Forces & motion","text":"Friction between surfaces produces...","options":{"A":"Electricity","B":"Magnetism","C":"Heat","D":"Cold"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0016","level":"ks2","subject":"physics","category":"Forces & motion","text":"On the Moon, gravity is weaker than on Earth. An astronaut on the Moon would weigh...","options":{"A":"More than on Earth","B":"The same as on Earth","C":"Nothing at all","D":"Less than on Earth"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_forces_motion_0017","level":"ks2","subject":"physics","category":"Forces & motion","text":"A pulley is a simple machine that helps to...","options":{"A":"Lift heavy objects more easily","B":"Create electricity","C":"Speed up vehicles","D":"Increase friction"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_motion_0018","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which of these has more water resistance — a narrow boat or a wide flat raft?","options":{"A":"The narrow boat","B":"The wide flat raft","C":"Both the same","D":"Neither — water has no resistance"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_forces_motion_0019","level":"ks2","subject":"physics","category":"Forces & motion","text":"When a small gear turns fast and is connected to a larger gear, the larger gear turns...","options":{"A":"At the same speed","B":"Faster","C":"Slower","D":"Not at all"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_forces_motion_0020","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which of these best describes what friction does?","options":{"A":"Speeds up moving objects","B":"Pulls objects towards the ground","C":"Pushes objects into the air","D":"Slows down or stops objects sliding"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_motion_0021","level":"ks2","subject":"physics","category":"Forces & motion","text":"A car with better streamlining needs less fuel because...","options":{"A":"Less air resistance means less energy is wasted","B":"More friction slows the car","C":"Gravity is reduced","D":"Water resistance increases"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_forces_motion_0022","level":"ks2","subject":"physics","category":"Forces & motion","text":"A falling object reaches a steady speed when...","options":{"A":"As soon as it starts falling","B":"Air resistance equals the pull of gravity","C":"It reaches the ground","D":"When gravity becomes zero"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_forces_motion_0023","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which object would fall MORE slowly through the air?","options":{"A":"A golf ball","B":"A cricket ball","C":"A large, open umbrella","D":"A rubber ball"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0024","level":"ks2","subject":"physics","category":"Forces & motion","text":"On a seesaw, a lighter child can balance a heavier child by sitting...","options":{"A":"Closer to the middle","B":"At the same distance from the middle","C":"Further from the middle","D":"On top of the heavier child"},"correct":"C","difficulty":2},
  {"id":"ks2_ph_forces_motion_0025","level":"ks2","subject":"physics","category":"Forces & motion","text":"What is the pivot (fulcrum) in a lever?","options":{"A":"The fixed point that the lever turns around","B":"The load being lifted","C":"The effort force applied","D":"The weight of the lever"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_forces_motion_0026","level":"ks2","subject":"physics","category":"Forces & motion","text":"An object sinks in water when...","options":{"A":"It is too light","B":"Gravity pulls it down more than the water pushes it up","C":"It is streamlined","D":"It is magnetic"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_forces_motion_0027","level":"ks2","subject":"physics","category":"Forces & motion","text":"Why do racing cyclists wear smooth, rounded helmets?","options":{"A":"To make them look better","B":"To protect against magnets","C":"To reduce air resistance","D":"To increase friction"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_forces_motion_0028","level":"ks2","subject":"physics","category":"Forces & motion","text":"Which of these situations involves the MOST friction?","options":{"A":"A ball rolling across a polished wooden floor","B":"An ice skate sliding on ice","C":"A boat moving through still water","D":"Dragging a rough rock across sandpaper"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_forces_motion_0029","level":"ks2","subject":"physics","category":"Forces & motion","text":"In a vacuum (no air), a heavy hammer and a light feather are dropped at the same time. What happens?","options":{"A":"They hit the ground at the same time","B":"The hammer lands first","C":"The feather lands first","D":"Neither falls"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_forces_motion_0030","level":"ks2","subject":"physics","category":"Forces & motion","text":"A gear system in a bicycle helps the rider to...","options":{"A":"Go in straight lines only","B":"Change the amount of force or speed needed to turn the wheels","C":"Make the brakes work","D":"Inflate the tyres"},"correct":"B","difficulty":2},

  # ── Earth & space ────────────────────────────────────────────────────────
  {"id":"ks2_ph_earth_space_0001","level":"ks2","subject":"physics","category":"Earth & space","text":"What shape is the Earth?","options":{"A":"A sphere (ball shape)","B":"Flat","C":"A cube","D":"An oval disc"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0002","level":"ks2","subject":"physics","category":"Earth & space","text":"What causes day and night?","options":{"A":"The Moon moving in front of the Sun","B":"The Earth spinning on its axis","C":"The Sun moving around the Earth","D":"Clouds blocking the Sun"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_earth_space_0003","level":"ks2","subject":"physics","category":"Earth & space","text":"How long does the Earth take to orbit (go around) the Sun once?","options":{"A":"One day","B":"One month","C":"One year","D":"One hour"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0004","level":"ks2","subject":"physics","category":"Earth & space","text":"Which of these is the closest star to Earth?","options":{"A":"The Moon","B":"Polaris (the North Star)","C":"Sirius","D":"The Sun"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0005","level":"ks2","subject":"physics","category":"Earth & space","text":"How long does the Earth take to spin once on its axis?","options":{"A":"24 hours (one day)","B":"One week","C":"One month","D":"One year"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0006","level":"ks2","subject":"physics","category":"Earth & space","text":"How does the Moon get the light we see at night?","options":{"A":"It makes its own light","B":"It reflects light from the Sun","C":"It gets light from other stars","D":"It glows from inside"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_earth_space_0007","level":"ks2","subject":"physics","category":"Earth & space","text":"How long does the Moon take to orbit the Earth once?","options":{"A":"One day","B":"One week","C":"About one month","D":"One year"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0008","level":"ks2","subject":"physics","category":"Earth & space","text":"Which planet is closest to the Sun?","options":{"A":"Earth","B":"Mars","C":"Venus","D":"Mercury"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0009","level":"ks2","subject":"physics","category":"Earth & space","text":"What is the Sun?","options":{"A":"A star at the centre of our Solar System","B":"A planet","C":"A moon of Earth","D":"A comet"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0010","level":"ks2","subject":"physics","category":"Earth & space","text":"Why is it daytime in the UK when it is night in Australia?","options":{"A":"Australia is closer to the Moon","B":"The Earth is rotating, so different parts face the Sun at different times","C":"Australia is on the other side of the Moon","D":"Australia has a different Sun"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_earth_space_0011","level":"ks2","subject":"physics","category":"Earth & space","text":"How many planets are in our Solar System?","options":{"A":"Six","B":"Seven","C":"Eight","D":"Nine"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0012","level":"ks2","subject":"physics","category":"Earth & space","text":"Which is the largest planet in our Solar System?","options":{"A":"Saturn","B":"Neptune","C":"Earth","D":"Jupiter"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0013","level":"ks2","subject":"physics","category":"Earth & space","text":"Earth's axis is tilted. This is the main reason we have...","options":{"A":"Seasons","B":"Day and night","C":"The phases of the Moon","D":"Tides"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_earth_space_0014","level":"ks2","subject":"physics","category":"Earth & space","text":"What does the word 'orbit' mean?","options":{"A":"Spin on an axis","B":"Travel around something (like Earth orbiting the Sun)","C":"Move in a straight line","D":"Stay still in space"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_earth_space_0015","level":"ks2","subject":"physics","category":"Earth & space","text":"The Moon does not produce its own light. The Moon is a...","options":{"A":"Star","B":"Planet","C":"Natural satellite of Earth","D":"Comet"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0016","level":"ks2","subject":"physics","category":"Earth & space","text":"What causes the phases of the Moon?","options":{"A":"The Moon moving into Earth's shadow","B":"Clouds covering the Moon","C":"The Moon spinning on its own axis","D":"How much of the Moon's lit side we can see from Earth"},"correct":"D","difficulty":2},
  {"id":"ks2_ph_earth_space_0017","level":"ks2","subject":"physics","category":"Earth & space","text":"Which planet is known as the Red Planet?","options":{"A":"Mars","B":"Venus","C":"Jupiter","D":"Saturn"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0018","level":"ks2","subject":"physics","category":"Earth & space","text":"How does the Sun appear to 'move' across the sky during the day?","options":{"A":"The Sun actually moves around the Earth","B":"The Earth rotates, making the Sun appear to move","C":"The Moon pushes the Sun","D":"Clouds move the Sun's reflection"},"correct":"B","difficulty":1},
  {"id":"ks2_ph_earth_space_0019","level":"ks2","subject":"physics","category":"Earth & space","text":"What is a Solar System?","options":{"A":"A way of using the Sun to make electricity","B":"A pattern of stars in the night sky","C":"A star and all the objects that orbit it","D":"The pattern of day and night"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0020","level":"ks2","subject":"physics","category":"Earth & space","text":"Which planet is surrounded by a famous ring system?","options":{"A":"Jupiter","B":"Mars","C":"Neptune","D":"Saturn"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0021","level":"ks2","subject":"physics","category":"Earth & space","text":"When you see stars at night, it means your side of Earth is...","options":{"A":"Facing away from the Sun","B":"Facing toward the Moon","C":"In Earth's shadow","D":"Moving away from the Sun"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0022","level":"ks2","subject":"physics","category":"Earth & space","text":"The Sun rises in the east because...","options":{"A":"The Sun moves from east to west","B":"Earth rotates from west to east, making the Sun appear to rise in the east","C":"The Moon pushes the Sun upward","D":"Gravity pulls the Sun eastward"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_earth_space_0023","level":"ks2","subject":"physics","category":"Earth & space","text":"Which of these statements about our Solar System is TRUE?","options":{"A":"The Sun orbits Earth","B":"The Moon is bigger than the Sun","C":"Earth orbits the Sun","D":"The Sun is a planet"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0024","level":"ks2","subject":"physics","category":"Earth & space","text":"A year on Earth is about 365 days. This is the time it takes for...","options":{"A":"The Moon to orbit the Earth once","B":"The Earth to spin once","C":"The Sun to move around Earth","D":"Earth to orbit the Sun once"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0025","level":"ks2","subject":"physics","category":"Earth & space","text":"Which is the correct order of planets from nearest to furthest from the Sun?","options":{"A":"Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune","B":"Mercury, Earth, Venus, Mars, Jupiter, Saturn, Uranus, Neptune","C":"Mercury, Venus, Earth, Mars, Saturn, Jupiter, Uranus, Neptune","D":"Venus, Mercury, Earth, Mars, Jupiter, Saturn, Uranus, Neptune"},"correct":"A","difficulty":2},
  {"id":"ks2_ph_earth_space_0026","level":"ks2","subject":"physics","category":"Earth & space","text":"Why is it warmer in summer than winter in the UK?","options":{"A":"The UK is closer to the Sun in summer","B":"The UK is tilted towards the Sun, so sunlight is stronger and days are longer","C":"There are more clouds in winter","D":"The Sun makes more heat in summer"},"correct":"B","difficulty":2},
  {"id":"ks2_ph_earth_space_0027","level":"ks2","subject":"physics","category":"Earth & space","text":"What is a star?","options":{"A":"A lump of rock orbiting a planet","B":"A cold dark object in space","C":"A huge ball of very hot gas that gives off light and heat","D":"A planet that is very bright"},"correct":"C","difficulty":1},
  {"id":"ks2_ph_earth_space_0028","level":"ks2","subject":"physics","category":"Earth & space","text":"The Moon appears to change shape each night. What do we call these changes?","options":{"A":"Eclipses","B":"Orbits","C":"Seasons","D":"Phases of the Moon"},"correct":"D","difficulty":1},
  {"id":"ks2_ph_earth_space_0029","level":"ks2","subject":"physics","category":"Earth & space","text":"What is the name of the galaxy our Solar System is in?","options":{"A":"The Milky Way","B":"The Andromeda Galaxy","C":"The Great Bear","D":"The Solar Galaxy"},"correct":"A","difficulty":1},
  {"id":"ks2_ph_earth_space_0030","level":"ks2","subject":"physics","category":"Earth & space","text":"What is a moon (natural satellite)?","options":{"A":"A star that orbits a planet","B":"A natural object that orbits a planet","C":"A small sun","D":"A comet that moves around the Earth"},"correct":"B","difficulty":1},
]

def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    backend_path = os.path.join(repo_root, "backend", "questions.json")
    frontend_path = os.path.join(repo_root, "src", "data", "questions.js")

    # ── 1. Verify no ks2_ph_* ids already exist ──────────────────────────
    with open(backend_path, encoding="utf-8") as f:
        existing = json.load(f)

    existing_ids = {q["id"] for q in existing}
    new_ids = {q["id"] for q in QUESTIONS}
    collisions = existing_ids & new_ids
    if collisions:
        print(f"ERROR: ID collisions found: {collisions}", file=sys.stderr)
        sys.exit(1)

    # ── 2. Print BEFORE counts ────────────────────────────────────────────
    before_counts = {}
    for q in existing:
        k = (q.get("subject", "?"), q.get("level", "?"))
        before_counts[k] = before_counts.get(k, 0) + 1

    print("BEFORE counts (subject, level):")
    for k in sorted(before_counts):
        print(f"  {k}: {before_counts[k]}")
    print(f"  TOTAL: {len(existing)}")

    # ── 3. Append to backend/questions.json ──────────────────────────────
    merged = existing + QUESTIONS
    with open(backend_path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, separators=(",", ":"))
    print(f"\nWrote {len(merged)} questions to {backend_path}")

    # ── 4. Append to src/data/questions.js ───────────────────────────────
    with open(frontend_path, encoding="utf-8") as f:
        js_content = f.read()

    # Build the new question lines (one per line, matching existing style)
    new_lines = "\n".join(
        "  " + json.dumps(q, ensure_ascii=False, separators=(",", ":"))
        for q in QUESTIONS
    )

    # Replace the closing `];` with the new block + `];`
    if not js_content.rstrip().endswith("];"):
        print("ERROR: questions.js does not end with ];\nCannot safely append.", file=sys.stderr)
        sys.exit(1)

    updated = js_content.rstrip()[:-2] + ",\n" + new_lines + "\n];"
    with open(frontend_path, "w", encoding="utf-8") as f:
        f.write(updated)
    print(f"Wrote {len(merged)} questions to {frontend_path}")

    # ── 5. Print AFTER counts and diff ───────────────────────────────────
    after_counts = {}
    for q in merged:
        k = (q.get("subject", "?"), q.get("level", "?"))
        after_counts[k] = after_counts.get(k, 0) + 1

    print("\nAFTER counts (subject, level):")
    for k in sorted(after_counts):
        diff = after_counts[k] - before_counts.get(k, 0)
        marker = f"  (+{diff})" if diff else ""
        print(f"  {k}: {after_counts[k]}{marker}")
    print(f"  TOTAL: {len(merged)}")

    # ── 6. Per-category breakdown for new questions ───────────────────────
    cat_counts = {}
    for q in QUESTIONS:
        cat_counts[q["category"]] = cat_counts.get(q["category"], 0) + 1
    print("\nNew KS2 Physics questions per category:")
    for cat, n in sorted(cat_counts.items()):
        print(f"  {cat}: {n}")
    print(f"  Total new: {len(QUESTIONS)}")

    print("\nDone. Verify: python -c \"import json; data=json.load(open('backend/questions.json',encoding='utf-8')); print(len(data))\"")

if __name__ == "__main__":
    main()
